name: "Deploy App"

on:
  push:
    tags:
      - "github-action-demo/*"

env:
  PROJ_PATH: github-action-demo/github-action-demo.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - run: dotnet restore ${{ env.PROJ_PATH }}

      - run: dotnet build ${{ env.PROJ_PATH }} -c Release --self-contained -r win-x86 -p:PublishSingleFile=true --no-restore

      - run: dotnet publish ${{ env.PROJ_PATH }} -c Release --self-contained -r win-x86 -p:PublishSingleFile=true --no-build

      - uses: actions/upload-artifact@v3
        with:
          name: github-action-demo.exe
          path: github-action-demo\bin\Release\net6.0-windows\win-x86\publish